# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradeCal', '0001_Added Student, Course, Test, Homework, Assignments entities with appropriate fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='overall_score',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='overall_assignment_percentage',
            new_name='assignment_percentage',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='overall_homework_percentage',
            new_name='homework_percentage',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='overall_test_percentage',
            new_name='test_percentage',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='overall_score',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='overall_score',
            new_name='max_score',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date',
            field=models.DateTimeField(verbose_name='Date Taken'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='date',
            field=models.DateTimeField(verbose_name='Date Taken'),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(verbose_name='Date Taken'),
        ),
    ]
