# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradeCal', '0003_auto_20160213_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assignment_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='homework_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='test_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
