# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradeCal', '0004_auto_20160213_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GradeAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('course_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradeCal.CourseAssessment')),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='course',
        ),
        migrations.RemoveField(
            model_name='test',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='assignment_percentage',
        ),
        migrations.RemoveField(
            model_name='course',
            name='homework_percentage',
        ),
        migrations.RemoveField(
            model_name='course',
            name='test_percentage',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='courseassessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradeCal.Course'),
        ),
    ]
